### ISSUE TITLE
Film Dump threads can be rated at 0.5 increments?

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#1023]
> Thought I'd drop a mention in here that 0.5-scale ratings are back in Film Dump. Enjoy!
> — [astral](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3909650&perpage=40&pagenumber=281#post507404072)

**Comment by dfsm** [comment]
The .5 scale ratings actually work fine in the app. Verified this while resolving the regular thread rating issue recently.

Astral's change would have changed the site to behave more like the app (which behaved like the site 9 years ago)
