### ISSUE TITLE
Duplicate smilies in smilie keyboard

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#1105]
> Unfortunately I still see duplicated smilies, even after logging out and back in (which causes the app to close)
> — [ZeeBoi](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=106#post516521334)

(This is after having fixed one way duplicate smilies could appear.)

**Comment by nolanw** [comment]
> 
> 
> FWIW, I’m also still seeing them, but I appreciate the efforts to fix it!![](https://fi.somethingawful.com/images/smilies/smile.gif)
> — [fartknocker](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=106#post516528601)

**Comment by nolanw** [comment]
> e2: A debug version built fresh from the main branch doesn’t have duplicate smileys, but the App Store version does - even after a delete and reinstall.
> 
> Duplicates are blank after deleting the app. Looks like they become dupes without images. But the debug version looks completely fine. Weird
> — [commie kong](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=106#post516540947)

**Comment by dfsm** [comment]
This was actually resolved, however some users needed to delete and reinstall the app. Anyone still experiencing this issue in 2022 likely hasn't reinstalled the app in years. Doing so should sort it for them.
