### ISSUE TITLE
Update link on GitHub header

### ISSUE THREAD

**Issue by eqprog** [Awful/Awful.app#1154]
The link in readme.md is correct, but the link at the top of the project is outdated. Correct link: https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=1

(Screenshot from GitHub app)
![image](https://user-images.githubusercontent.com/66541216/185757701-103fa390-3697-4a23-bdf4-1c3c1647009b.jpeg)

**Comment by nolanw** [comment]
Fixed, thank you!
