### ISSUE TITLE
Awful for Mac

### ISSUE THREAD

**Issue by eschaton** [Awful/Awful.app#141]
I love the Awful experience — enough that I'd prefer it on my Mac, too, compared to the raw site.

**Comment by nolanw** [comment]
Reopening but this is not an announcement of anything :)

**Comment by eschaton** [comment]
Any chance of building and posting Mac Catalyst builds as GitHub releases via Developer ID signing? :)

**Comment by nolanw** [comment]
@eschaton Now that 4.0 is out my plan is to out a lil build script together and get that train rolling :)

**Comment by eschaton** [comment]
Hey, I’ve used Awful a bit on an M1 Mac, how about just shipping Catalyst builds for Intel via GitHub at this point? It doesn’t really need tweaking to work acceptably, and the easiest way to find where to tweak will be to get people using it.

**Comment by nolanw** [comment]
@eschaton Done! I'm happy to take any Catalyst-specific issues as new issues, with the usual Awful commitment of "these may never be fixed". And I appreciate the years of prodding and patience :)
