### ISSUE TITLE
Thread tag picker scrolling is laggy

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#284]
Fix that up.

Random guess: [FastImageCache](https://github.com/path/FastImageCache) claims to solve similar issues, take a look at that maybe.

**Comment by nolanw** [comment]
Is this still a thing? I don't remember addressing it.

**Comment by realModusOperandi** [comment]
I've only noticed a speed issue when initially loading the tags. Once they're all loaded in, it's smooth. Sounds like that matches the bug description.

**Comment by nolanw** [comment]
Recently hooked up Nuke and using it in the thread tag picker screen seems to have eliminated all jank. Happy to hear from anyone who finds otherwise!
