### ISSUE TITLE
Ease up on the "pull for next page of posts" gesture when generally scrolling

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#337]
> Would it be possible to make the "keep scrolling at the bottom of the page to go to the next one" thing less sensitive? Or maybe put in some sort of delay (something like, when you're scrolling and you hit the end of the page, it doesn't trigger until it comes to a stop and you pull up again?) I keep missing the last couple posts on every page, because I apparently scroll too fast :( If neither of those are doable, could we at least get an option to turn it off in settings?

> My dream is to not make pull to load a new page activate the first time I hit the bottom of a page. Sometimes I'm trying to back track to the end of a page and after everything loads I find I hit the bottom too hard and it loaded the next.

> Is there a way to not go to the next page/reload the page if I scroll all the way down to the bottom? It's happened too much where I'm scrolling down to get to the bottom and accidentally pull too hard/much and either go on to the next page or reload and end up at the top again.

> Can 'pull to load next page' be a toggle in settings please I've jumped to the next page twice in literally the last 30 seconds before reading the last two posts on the page

> when scrolling down a page, often I'll miss the last two or three posts because it'll launch the next page. Some kind of an indicator that you're getting to the end of a page would be nice' forcing users to release and swipe down further to get the app to launch the next page would be better.

**Comment by realModusOperandi** [comment]
I'm trying to mitigate this by requiring the state to be `triggered` in order for it to enter `refreshing` instead of just having the `maxVisibleY` be greater than the `frame.maxY`. In other words, you have to be actively pulling instead of just happening to get past the threshold on inertia.

If this doesn't work, I'll look only allowing into the `triggered` state if the pan gesture started at the bottom of the visible page or something.

**Comment by nolanw** [comment]
I haven’t looked at the code in awhile but the general approach sounds right.

In the past I’ve had success implementing scrollViewWillEndDragging and checking the target content offset. Might be another option, plus we can do away with the redundant gesture recognizer.

**Comment by realModusOperandi** [comment]
Sure, but we might want to move that gesture recognizer to the posts view itself and use it to skip jumping to a spot on the page if the users have already scrolled at least once.

**Comment by nolanw** [comment]
> About the scrolling and accidentally loading the next page thing, what the Android app does is allow you to set the percentage of the screen you need to scroll. I bumped it up a bit slightly from the default and no longer get accidental new pages in that one. The ios app seems to be around 10-15 percent maybe, or at least whatever it is for me is rather low so I accidentally go to the next page a lot. Maybe make that configurable perhaps?
> —[shortspecialbus](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481865772)

> This would be great.
> — [IllegallySober](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481867869)

> I'm going to dissent and say that while it certainly needs to be adjusted, making it a user setting is a terrible way to "fix" the problem.
> — [Diabolik900](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481868641)

**Comment by nolanw** [comment]
> Well, I like [pull for next page], I just don't like it triggering with such a small pull is all. Or at least not when I start my scroll when I'm not at the bottom of the page - maybe have it not do the pull for next page if you weren't already at the bottom of the page when you do your scroll? That might solve the problem itself, if it would be feasible.
> — [shortspecialbus](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481870139)

**Comment by nolanw** [comment]
> I didn't notice the hyper-sensitivity as much until I switched to my X so I dunno if it's more sensitive depending on device, but anecdotally for me, that was the case.
> — [IllegallySober](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481872261)

**Comment by nolanw** [comment]
> It’s pretty good for me. maybe if it was a user set it 5% higher. More interestingly, you go read a page with just 1 new post and 39 previous posts not showing, it’s almost impossible to pull up to the next page. You need to pull up by over half the screen length.
> — [Billzasilver](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481872438)

**Comment by nolanw** [comment]
> Coming up with a good default would be a combination of considering "where do users usally put text when they're reading a page" (when I'm reading I usually scroll to put what I'm reading near the center) and "giving the user enough time to react to hitting the end of the page to say 'oh shit it's the end' and either stop scrolling, or to scroll back down before lifting their finger up so that the page jump doesn't occur".
> 
> My spitball solution would involve leaving the 10-15% if the last post of the page is already fully visible (ie, the user already has hit the bottom of the page and actively wants to move to the next one) and increasing it to 30%+ if not (in the situation that they're just scrolling down the page and don't realize they're at the end of it already). Alternatively (or perhaps in addition) adding a visible "next page" prompt/icon that's always shown at the bottom of the last post on a page as a visual indication that continuing to scroll will trigger it, as opposed to only showing it in the small window of "you're scrolling past the last post but haven't hit the next page trigger yet"-- "End of Thread" already has this, so I kind of wonder what the frequency is of "accidentally jumping to the next page" vs. "unintentionally refreshing the thread on the last post" is...
> 
> I'm also in the "I hit it too many times and just turned the option off" camp.
> — [Ursine Catastrophe](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481877957)

**Comment by nolanw** [comment]
> I normally read towards the top of a page. I think this would be different for everyone.
> 
> How about the last post has say, half a screen of blank space underneath it. Like a buffer that you need to scroll through before beginning the pull to next page trigger. I think that absence of text would be visible enough in the peripheral vision for the user to realise they've reached the end so they'd be more conscious of scrolling further. Like how it is when you open a previously read thread and there are only 1/2 posts left.
> — [spanky the dolphin](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=12#post481878284)

**Comment by nolanw** [comment]
> I'm cool with [making it hard to accidentally trigger the thing] -- like maybe 25% of screen height, instead of what it is now?
> — [kimbo305](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=15#post482969921)

> Yes please.
> — [IllegallySober](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=15#post482971043)

**Comment by nolanw** [comment]
> Sorry to bring this up again but I gave my wife my Android tablet so I'm using the iPad Pro more and I'm still consistently moving to the next page in a thread accidentally. I don't want to disable swipe for next page, but I think we'd talked about maybe it needing to be a bit more of a distance or something? Are there any plans in the near future to maybe implement something along those lines? I won't ask for an adjustable setting this time I promise.
> — [shortspecialbus](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=19#post486105241)

**Comment by nolanw** [comment]
> Is it possible to make the “pull up for next page” less touchy? A lot of times when I’m scrolling through a thread, just scrolling to the bottom will trigger it and I’ll miss the last post-two on that page
> — [Sockser](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=24#post488252019)

**Comment by nolanw** [comment]
> I feel like I run into this a lot. 
> 
> Having to pull the page up a bit more to trigger the next page would be awesome.
> — [BromanderData](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=24#post488252201)

**Comment by nolanw** [comment]
> I feel like it should only take effect if you're at the bottom of the page and not currently scrolling. How hard would that be to detect and implement?
> 
> My only problem with pull-for-next-page is when I'm cruising down to the bottom of the page and accidentally swipe up because I either still have scroll momentum going or I'm on autopilot and hit the bottom half a second ago.
> — [Data Graham](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=26#post488724600)

**Comment by nolanw** [comment]
Haven't heard complaints for awhile, and there's a setting now to turn it off too. Happy to entertain new issues if it comes up again.
