### ISSUE TITLE
Crash first time logging back in after logging out

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#348]
> Was getting warnings about my cookie about to expire. I guess it expired then today, as I started getting cryptic error messages when trying to load any thread. No problem, I'll just log out and then log back in. When I logged back in, there was a crash to springboard. Then when I opened Awful, all my settings were reverted to default. 5S, 9.3.2, latest App Store version.
> — Awful 3.13

> I always crash when I try to log back in. Latest release of Awful, latest iOS, iPhone SE. Right after hitting "Log In", Awful thinks for a moment then crashes. Reopening it takes me back to the login screen after which I can log in just fine, but when I do, Awful has been completely reset. Favorite forums, all the settings are back to default.

> 3.16 SE if I log out, the app crashes the first time I try to log back in. Works just fine the second time

**Comment by nolanw** [comment]
> I just had the app require me to relogin, then it crashed as soon as I logged in. Then I had to login again and now it forgot all my settings
> — [Jose Valasquez](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3564303&perpage=40&pagenumber=66#post476173321)

> :same:
> — [emoji](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3564303&perpage=40&pagenumber=66#post476173352)

**Comment by nolanw** [comment]
> Have a super annoying bug - seems to be impossible to log out and then log in with a different account - first, it will crash upon initial login attempt with second account. Then, sometimes I’m able to log in, other times, it will seemingly work, but it’s actually logged into the initial account, so posts end up on the wrong account if I don’t immediately notice.
> 
> When that happens, I can’t click on the settings inside awful, it crashes 100% of the time. So I have to uninstall and reinstall to switch accounts now :-(
> 
> E: iOS 12.1 on iPhone 7+
> — [Slothful Bong](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=34#post490356891)

**Comment by nolanw** [comment]
> Update to my multi-user crashing bug - the newest official Awful (3.45) seems to now let me successfully log into other accounts, but it does still crash about 3/4 of the time when clicking the logout button, or logging out, then entering in another account (it crashes from the login screen, and you have to enter in the info a second time to actually log in).
> 
> But unlike before, I don’t seem to have to uninstall to switch accounts, and I don’t seem to be getting the issue where I’d log into one account, go to another app, then come back and have it be on the original account instead.
> 
> E: just realized this issue seems to happen when Awful loses focus, ie from a crash.
> — [Slothful Bong](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=35#post490411213)

**Comment by nolanw** [comment]
> Got logged out after using the new TestFlight version of Awful last night, it crashed when I logged in, and then worked okay the second login attempt except that it forgot all my settings besides the app icon (:ghost:4ever).
> — [Grace Baiting](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=124#post522436908)

**Comment by dfsm** [comment]
Crash resolved in [b58f435](https://github.com/Awful/Awful.app/commit/b58f435c93cc8aef099a6ae8e9934099ee32ef5d)

_Fixed two crash causes experienced during login after logging out. 1. Core data attempt to merge changes now checks for hasChanges first. 1. loginViewController nil when Log Out button pressed. Now creating login VC in logOut method._

The forgetting of settings is not related to the crash and is currently the intended functionality of the logging out function. Will seek to address loss of settings under a different issue
