### ISSUE TITLE
iOS 11: iPad tabs crowd each other out

### ISSUE THREAD

**Issue by realModusOperandi** [Awful/Awful.app#357]
It's not just us; it happens on iOS 11 any time a tab view is inside a split view and that split view is set to autohide.

![img_0183](https://user-images.githubusercontent.com/1577201/28997448-d69a8602-79da-11e7-8eac-a1167568bd1b.PNG)

I filed a bug with Apple. I'll use this issue to relay any updates. If they don't fix it by next month we'll need to look into fixing it ourselves.

**Comment by nolanw** [comment]
I'm on board with ditching UISplitViewController. Gives us some more flexibility to deal with collapse/always show sidebar settings, and might end up simplifying all the split view stupidity we do now.

**Comment by realModusOperandi** [comment]
Well, Apple seems to have ignored this one. It's still present in the latest betas of iOS, and Xcode itself hasn't been updated for 3 weeks now so I assume that's the GM driver already. Of course I assumed there would be builds called "Release Candidates." I dont know where I got that idea from.

Meaning we probably have to come up with some sort of alternative to the whole layout on the iPad. How much effort would it be to do away with one or both of these things? I assume a lot but I'm just not sure what to do in the short term.

This UI pattern must not be very common--it's easily reproducible in a test project, but I can't find a single complaint about the bug online.

**Comment by nolanw** [comment]
I just took a wander through the API diffs and didn’t see anything relevant, fwiw.

It’s possible we could muck with the trait collection of the UITabBarController to convince it to stack the bar items vertically (maybe it responds to regular vs. compact width?) or subclass something in there to get the behaviour we want. I’m not above doing something undocumented while we find a more stable fix.

It would be a nontrivial effort to redo the iPad layout and/or make our own split view controller and tab bar controller, but it wouldn’t be the first time I’ve done either, so I think I’m up for the challenge. I’ve had "ditch UISplitViewController" on my list for awhile because we already bathe it in hacks just to get it working as we want today, so making our own feels somehow less precarious. But I’m guessing that’s not gonna fix the tabs.

Did you file a radar? If you have an example project, someone will look at it.

**Comment by realModusOperandi** [comment]
I've had a radar open since beta 3 or 4, with the minimal reproduction project included. No action that I can see on my end since late July.

I've been playing around with trying to set various properties on the tab bar unsuccessfully. The odd thing is, there's zero mention of this behavior anywhere in the TabBar docs. Regular vs compact might be the key, but I get the sense the bar is incorrectly being told it's regular size class when the master view is set to hover. Maybe that's the first avenue to explore in mitigating this?

**Comment by nolanw** [comment]
Ah right on. Sounds like the typical radar experience :/ Might be worth a poke "still happening in beta 10" but you’ve done your part I think.

We could look at subclassing UISplitViewController and overriding/mucking with `overrideTraitCollection(forChildViewController:)` and `setOverrideTraitCollection(_:forChildViewController:)`?

**Comment by nolanw** [comment]
Does a combination of https://stackoverflow.com/a/45945937/1063051 and https://stackoverflow.com/a/46193806/1063051 work?

**Comment by realModusOperandi** [comment]
We don't currently instantiate the UITabBar directly but I'll see if I can crowbar that in somewhere

**Comment by nolanw** [comment]
Another possibly useful tidbit:
> In your storyboard, set your UITabBarController's tab bar's class to HidingTabBar. There is literally no way to do this in code or a regular xib.
> —  https://github.com/bnickel/HidingTabBar

So maybe we can subclass, use a storyboard to load the tab bar controller, then muck with the trait collection in the subclass?

I’ll give this a try unless someone beats me to it.

**Comment by realModusOperandi** [comment]
Go for it, I'm neck deep in settingsbinding related stuff for the alternate app icon feature.

**Comment by nolanw** [comment]
Ooh, sorry. Feel free to throw that crap out if it’s not doing its job.

**Comment by realModusOperandi** [comment]
It's not bad but I'm finally back to a point where I remember where everything has to be changed to make it work :)

**Comment by nolanw** [comment]
@realModusOperandi got a radar number and/or [Open Radar](http://openradar.appspot.com) link I can paste in to the comments near the code?

**Comment by nolanw** [comment]
UITabBarController is such a shitshow. I have never put it into an app without hating life, whether it's something like this or trying to hide/show the tab bar at certain times. Ugh. Anyway, that last idea worked :toot:

**Comment by realModusOperandi** [comment]
rdar://33511602. I just copied everything over to that OpenRadar. Maybe that'll get some more eyes on it.
