### ISSUE TITLE
Maintain selected thread tag when cancelling out of picker in compose screen

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#360]
> If you're making a thread and choose a thread tag (say, "request"), then if you open the list of tags again thinking you'll want to change it to something else and hit cancel, it removes the first selection and leaves you with the shit post tag. I'd think canceling it would retain the original selection since you're canceling the dialog and not intentionally clearing it

**Comment by realModusOperandi** [comment]
This doesn't appear to occur for me. Pressing cancel leaves the thread tag I'd picked before. However, I did not post the thread, so I couldn't say if it was retained behind the scenes or not.

**Comment by nolanw** [comment]
Good enough for me!
