### ISSUE TITLE
Thread list scroll performance isn't great

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#370]
> Inertial scroll of the bookmark list is fairly janky on my 5S (iOS 8).

> scrolling through the list of threads is really choppy occasionally.
> — Awful 3.6, iPhone 4S, iOS 9

> 5s, latest iOS. The new versions seem to be...jittery. Whenever I scroll through threads, the scrolling is very stilted. Awful was completely smooth before this updafe. It's slight, and not a deal breaker, but I've never seen this in any iOS app. Anybody else seeing this?

> It is pretty bad on my 5S. Every time a page is loading scrolling leads to stutters. If I wait about 10 seconds when loading a page it clears up. Definitely has something to do with loading a new page.

**Comment by realModusOperandi** [comment]
I believe this was fixed with [this commit](https://github.com/Awful/Awful.app/commit/84ba5a4a6d8b56332123d00c52a828ef6d408f53).

**Comment by nolanw** [comment]
Yay!
