### ISSUE TITLE
Fix silliness with spoiler-tagged gifs

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#374]
Example: https://forums.somethingawful.com/showthread.php?threadid=3692371&perpage=40&pagenumber=33#post441459193

**Comment by realModusOperandi** [comment]
What's the silliness? Not sure what I'm looking for but I noticed nothing I didn't expect in that example.

**Comment by nolanw** [comment]
Apparently I thought that was enough to go on. Possibly some combination of the play indicator, spoilers, one toggles before the other? Could've been something that has since been fixed, some of these issues date back years.

Only thing coming to mind is maybe you can see the play button while the thing is unspoiled? If that's not the case then I say we close this issue.

**Comment by nolanw** [comment]
Silliness item one: play button appears when GIF is behind spoiler tags.
![play-spoilered-gif](https://user-images.githubusercontent.com/177228/52456429-135d9900-2b2b-11e9-9ddc-dcc683ef5ba5.png)

Silliness item two: can't ever play that GIF, because tapping always toggles the spoiler tag.
