### ISSUE TITLE
Don't crash when deleting favorite forums

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#375]
> I accidentally favorited a forum, and now whenever I try to delete it, the app crashes. Is there anything I can do to fix it?

> For whatever reason I seem to have favorited a forum so it appears at the top of the forums listing. Awful crashes when I try to delete from within the app.

**Comment by realModusOperandi** [comment]
Cursory testing says this works now.

**Comment by nolanw** [comment]
Sounds good to me. Will reopen if I find other reports.
