### ISSUE TITLE
Allow overriding choice of img or timg tag when posting

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#443]
> would it be possible to have a settings choice as to whether the imgur uploaded images appear in img or timg tags? […] mostly just in the yospos cat thread"

> I was posting large size web comics into the GBS web comics thread, where some people frown upon timg due to how it reacts when the forum is viewed on touchscreen devices in a normal web browser.

> If there isn't an option to embed images from my phone's library not as timg automatically but img instead already, can their be one?

> It would be cool to have some sort of "image scale preview" so I can tell if I am about to break tables for non-mobile users. Not sure what form would be best, if it's difficult or even possible. Maybe it could be a text indicator of image HxW versus table limit.

**Comment by nolanw** [comment]
Current behaviour is to follow forum rules, anything exceeding the size in the rules is automatically a timg. But some threads loosen that rule.

**Comment by nolanw** [comment]
> Please add an option to turn off auto timg
> — [Crime on a Dime](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=2#post477634003)

**Comment by nolanw** [comment]
> If I post a picture using the awful app is it automatically a timg? I am super late to the game and just noticed that posting images directly from my phone was an option.
> — [Hot Dog Day #82](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=6#post478980898)

**Comment by nolanw** [comment]
> Feature / option request: please allow disable of auto TIMG
> — [Crime on a Dime](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=9#post480307332)

**Comment by nolanw** [comment]
> Is there a way to stop the automatic timg?
> — [tyler d00rden](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=15#post483284825)

> would also like to know this
> — [scary ghost dog](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=15#post483285451)

**Comment by nolanw** [comment]
> Can you please add an option in settings to turn off auto timg?
> — [tyler](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=16#post484878964)

**Comment by nolanw** [comment]
> Please disable auto timg or add an option to disable it. It's been brought up before but sometimes the wheel's gotta squeak
> — [Crime on a Dime](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=21#post487059675)

**Comment by nolanw** [comment]
> Same. Otherwise great stuff keep it up!
> — [Mr. Nice!](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=21#post487061402)

**Comment by nolanw** [comment]
> no timg allowed in fyad
> — [Crime on a Dime](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=21#post487074290)

> Could make it forum-keyed, like autocapitalize is.
> — [Subjunctive](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=21#post487074726)

**Comment by nolanw** [comment]
> [maybe add an auto-timg toggle in settings] This. I’m tired of having to use the browser every time I want to post a picture
> — [tyler](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=21#post487278464)

**Comment by aidan-waite** [comment]
PR: https://github.com/Awful/Awful.app/pull/810

**Comment by nolanw** [comment]
Fixed in #810!
