### ISSUE TITLE
Private message/thread compose text box gets obstructed by keyboard

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#639]
> I can't remember seeing this but I just noticed when I'm looking at and replying to PMs in landscape mode, the keyboard covers the message if it's big enough and it won't scroll down to allow visibility for the part where the typing is going. Switching to portrait it seems to work then switching back to landscape seemed to make it scroll (but then I ran into another problem where the keyboard non-letter keys stopped working which could be an iOS thing). Sorry if this is a repeat! Tried it on both my new iPad and old one and same issue exists.
> — [Stoca Zola](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3510131&perpage=40&pagenumber=256#post475460332)

**Comment by nolanw** [comment]
(Thought we maybe had another report but seems to be different.)

**Comment by realModusOperandi** [comment]
"iPad only" not valid anymore?
>i just sent a pm and the keyboard covers half the body in the pm screen with no way to scroll to see the lower half.
- [baram.](https://forums.somethingawful.com/showthread.php?threadid=3510131&pagenumber=257#post476354952)

> It's when you're writing it. Basically it gets to the point that you have no idea what you're typing anymore.

>>Are you using the split keyboard on an ipad
>nah just an iphone 7
-[Over There](https://forums.somethingawful.com/showthread.php?threadid=3510131&pagenumber=257#post476367767)

**Comment by nolanw** [comment]
Not just PMs either.

> I found some steps to reproduce a bug that may be this bug, or may be distinct. If you begin making a post in a thread that includes at least 3 paragraphs (e.g. the body of your post is the string "1\n2\n3"), preview it, and then return to the compose view, your new post is now vulnerable to iterative layout destruction. Start to swipe from the right edge inwards, as if to go to your post's preview, but release partway through so you stay on the compose view; the text of your reply will now abruptly and permanently drop by roughly a line below where it should be. This effect can stack such that the usable text area hides below the keyboard and you can no longer see what you're typing. 
> 
> Even activating this once or twice and then typing more than a single screenful will prevent you from seeing or easily editing the last line or two of your post. (If this is the same bug that you saw, fruit on the bottom, then I'd guess this is how you experienced it.)
> 
> This bugged state persists until you entirely destroy the post by returning to a thread list view and tapping on a thread. If you've pushed your post's top border below the keyboard, you can't even copy the text + BBCode markup you'd been working on, since the "Select | Select All | [etc]" bubble stays behind the keyboard or possibly even below the physical edge of the screen. If you've inadvertently gotten to this bad state, I think the best you can do to preserve your post is preview it and select all + copy the rendered post's text (sans markup... or  if that suits your fancy I guess! Then you can probably edit it if necessary.)
> — [Grace Baiting](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3510131&perpage=40&pagenumber=257#post475854368)

**Comment by nolanw** [comment]
> Anyone else have the thing where you can’t scroll while writing a PM? I can force the screen to “scroll” by hitting return a bunch of times, but otherwise I can’t scroll up and down and if I write enough (or if I’m quoting someone) the text just goes under the keyboard and I can’t see what I wrote anymore.
> — [Pirate Radar](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=15#post483482737)

**Comment by nolanw** [comment]
> when replying to a PM, the text area doesn’t resize out of the way of the keyboard, so you end up with text and caret hidden underneath it.
> — [Subjunctive](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=19#post486354192)
