### ISSUE TITLE
Status bar disappears in Safari view controller

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#645]
### Steps to reproduce

1. Be in a light theme and set links to open in Awful.
2. Go to a thread with a post with a link to some webpage.
3. Tap link.

### Expected result

Safari view controller opens and I can see the status bar.

### Observed result

Safari view controller opens and there is no status bar.

### Notes

I suspect this is a result of #643 and the status bar is maintaining the light content we set at launch. Safari view controller presumably does the status bar stuff assuming its view controller-controlled.

I'm using Awful version 3.27 beta 1 on an iPad Air 2 running iOS 11.0 beta 10.

**Comment by realModusOperandi** [comment]
Haha, I had a feeling there'd be _something_ that had an issue with my change. I'll look into it.

**Comment by nolanw** [comment]
Swapped some UIApplication for some needsStatusBarUpdate and give it a quick try, seemed to work ok? Feels too simple, I'm probably missing something.

**Comment by nolanw** [comment]
Maybe the order was important and moving the status bar update down the animation block was the answer? So you basically fixed it by putting the UIApplication property set further down, which I then replaced with status bar update?

**Comment by realModusOperandi** [comment]
Hmm, maybe. It still happens for me if I open the preview in portrait on iOS 10. If I open it in landscape (whether I rotate to portrait or not afterwards) it works fine.
