### ISSUE TITLE
Xcode 9 wants a 1024px "iOS marketing" icon

### ISSUE THREAD

**Issue by realModusOperandi** [Awful/Awful.app#653]
The AppIcon section of Images.xcassets now has a space for a 1024x1024@1x App store icon.

Perhaps a generous designer could contribute one?

**Comment by nolanw** [comment]
I think spanky made the current icon, could probably ask them in the thread.

**Comment by realModusOperandi** [comment]
Yeah, that's where I'm headed right now. Just thought I'd file the issue too to track it.

**Comment by nolanw** [comment]
:discourse:

**Comment by realModusOperandi** [comment]
Added.
