### ISSUE TITLE
"Image Upload Failed" has no buttons

### ISSUE THREAD

**Issue by realModusOperandi** [Awful/Awful.app#658]
>iphone 7 on ios 11
>
>the errors for image upload no longer have an ok button so i have to force quit to regain control

-[Casual Encountress](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3510131&perpage=40&pagenumber=258#post476660921)

> Yeah, I had that last night, very annoying.
![Screenshot of problem](https://i.imgur.com/nWPWjTK.jpg)

-[The_Doctor](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3510131&perpage=40&pagenumber=258#post476680089)

**Comment by realModusOperandi** [comment]
Odd that the button wasn't being added automatically, it was when I tried to reproduce the problem elsewhere in the code.

**Comment by nolanw** [comment]
I'm not sure I even knew it would automatically add an OK button! Seems like a perfectly reasonable fix though so I think we can close this?
