### ISSUE TITLE
Thread list scrolling is janky, dropping frames

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#753]
Profile that and see what's up!

Noticed on iPad Air 2, Awful 3.35.

**Comment by elindsey** [comment]
Looked at this a bit, and it's likely IO from the thread images. There's very little CPU use; disabling thread images makes scrollperf crazy good. So probably we're synchronously grabbing those from disk and heading straight to janksville.

**Comment by nolanw** [comment]
I’m not entirely sure why I hand-rolled the thread tag image cache. If I was starting it today I’d grab an image caching library off the shelf; I’ve used [Kingfisher](https://github.com/onevcat/Kingfisher) a bunch and it seems alright. No shortage of choices in the genre. Any half-decent library will move IO off the main thread and will do other handy things like decode the image just before display.

Maybe it’s time to rip out the thread tag cache and wedge a library in there. Might end up being less pain overall compared to home-rolled background queue image updates that result in hilarious reuse bugs etc.

**Comment by nolanw** [comment]
> chop still exists while scrolling on the bookmark page.
> — [ratbert90](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=34#post490145710)

**Comment by nolanw** [comment]
Hooked up Nuke in a recent commit, seems much better now, so I'ma close this!
