### ISSUE TITLE
postimg.org is now postimg.cc, we should redirect image loads

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#760]
> Hey, I've noticed that images hosted on postimg.org are no longer working as their domain has been changed to postimg.cc
> …
> Quite a lot in this thread https://forums.somethingawful.com/showthread.php?threadid=3822798&pagenumber=54&perpage=40#post474484104
> — [gibb3h](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3571717&perpage=40&pagenumber=121#post483620548)

**Comment by nolanw** [comment]
We already muck around with Minus and Waffleimages, check those for examples!

**Comment by nolanw** [comment]
This was completed in the above PR!

**Comment by turtlemaster19** [comment]
I disagree that this is complete, s28.postimg.org/izfucxl3x/Untitled_1.png isn't correctly redirecting to https://postimg.cc/0bSpj0v1 unless you know to change the `.org` to `.cc` in the first URL

**Comment by osama202** [comment]
hi
