### ISSUE TITLE
Twitter embeds won't play videos or GIFs

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#772]
> I’m having trouble playing twitter videos or gifs while in the awful app. As in pressing play doesn’t do anything at all and I have to click the date to open the tweet in Twitter in order to watch anything.
> — [boop the snoot](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=17#post485333786)

Could maybe embed or grab latest .js from https://platform.twitter.com/widgets.js and keep it up to date? Check [Twitter docs](https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/set-up-twitter-for-websites) for ideas too. (h/t Sereri)

**Comment by nolanw** [comment]
I've been seeing this too.

**Comment by nolanw** [comment]
> Might be time to update the Twitter js again...
> — [carry on then](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=17#post485335451)

**Comment by nolanw** [comment]
> Came in here to post about probs with Twitter gifs/vids loading - looks like that’s already been covered. 
> — [Hervey Keith](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=17#post485403351)

**Comment by nolanw** [comment]
> Has anyone posted about twitter video embeds being fucked up? When I click on one I get a nice little setup with a play button and a time bar and stuff but the video won't actually play and none of the buttons do anything
> — [goferchan](https://forums.somethingawful.com/showthread.php?threadid=3837546&userid=0&perpage=40&pagenumber=21#post487160550)

**Comment by JonET** [comment]
I tried grabbing the latest widgets.js and didn't see a different in behavior. The iframe that's created grabs some videoplayer javascript that I suspect is the culprit.

**Comment by nolanw** [comment]
> Is everyone else still having trouble playing embedded twitter videos?
> — [Raged](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=23#post487875306)

**Comment by nolanw** [comment]
> I have noticed all other iOS apps (like Chrome/Safari) have an additional privacy button that is not appearing when using Awful. Don’t know if that’s helpful, but wanted to point that out.
> — [Wise Fwom Yo Gwave](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=23#post487887736)

**Comment by nolanw** [comment]
> Website with an embedded video tweet: 
https://www.wweek.com/news/2018/09/12/portland-thunderstorm-turns-laurelhurst-streets-into-ponds/
> — [anthonypants](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=23#post487917003)

> Screenshots of those views in the app:
> ![](https://user-images.githubusercontent.com/177228/45656671-21981380-babd-11e8-9379-e0f58cf75ad8.png)
> and in safari:
> ![](https://user-images.githubusercontent.com/177228/45656679-2957b800-babd-11e8-8fd2-393629408b87.png)
> — [anthonypants](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=23#post487917111)

> And my first click:
> ![](https://user-images.githubusercontent.com/177228/45656703-47251d00-babd-11e8-980f-11ffdadda0c6.png)
> — [Wise Fwom Yo Gwave](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=23#post487917199)

**Comment by nolanw** [comment]
> Videos don't play; you can tap to "activate" a video, but then it never starts playing
> — [Data Graham](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=25#post488702044)

**Comment by nolanw** [comment]
Seems to be fixed by #669.
