### ISSUE TITLE
Convert to Swift 4.2

### ISSUE THREAD

**Issue by realModusOperandi** [Awful/Awful.app#789]
Opening this issue to keep track of the state of things.

Currently, Travis has created an xcode10 image with beta 6, and the swift-4.2 branch is green on that image. I'll continue to keep up to date with both updates to master here and updates to the Xcode and iOS betas. Once Apple eGAs iOS 12 and I get everything merged up and tested with the GM drivers we can figure out when/if we want to merge these changes into master.

**Comment by nolanw** [comment]
This got done, I forgot to close the issue though!
