### ISSUE TITLE
Avoid content jumping around when switching away from OLED theme

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#908]
> Could we get a light version of the OLED theme, so that content doesn’t jump around when it auto-switches?
> — [Subjunctive](https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3837546&perpage=40&pagenumber=53#post496264563)

**Comment by shaver** [comment]
This was done in 02c8cba406ef5f70e933337d7c6562699c2a3f48
