### ISSUE TITLE
New action icons

### ISSUE THREAD

**Issue by nolanw** [Awful/Awful.app#924]
> Hey I've output all these icons [into this folder.](https://drive.google.com/open?id=1R1lEoKaxT7qrw6jqOjsY6PZWpq250uCv)
>  
>  ...
>  
>  There are some brand new icons too. I've separated 'report' and 'rap-sheet' into 2 icons. There's an updated 'copy-title' icon - I didn't make the original one of these so I don't know if the naming is correct. There's a 'cancel' icon for putting at the bottom of the steamed-ham menu. There's also a parent-forum icon if you want to try putting that in steamed-ham.
> — [spanky the dolphin](https://forums.somethingawful.com/showthread.php?threadid=3837546&perpage=40&pagenumber=58#post498229911)

**Comment by nolanw** [comment]
> Hey Pokey, great work as per usual. Could you please +1 updating the [icons](https://drive.google.com/drive/folders/1R1lEoKaxT7qrw6jqOjsY6PZWpq250uCv) I made a while ago? Thank ye.
> — [spanky the dolphin](https://forums.somethingawful.com/showthread.php?threadid=3837546&perpage=40&pagenumber=64#post500260560)

**Comment by dfsm** [comment]
I've added all of spanky's icons!
