### ISSUE TITLE
New FYAD(forumid 666) doesn't use the pink stylesheet and autocorrect is on

### ISSUE THREAD

**Issue by JeffreyOfYOSPOS** [Awful/Awful.app#969]
### Steps to reproduce

1. Launch Awful.
2. Go to new FYAD, forumid 666.
3. Start making a post

### Expected result
1. Forum is pink.
2. Autocorrect and stuff is turned off.

### Observed result
1. Forum is not pink.
2. Autocorrect is on.

### Notes
I don't use an iphone this is someone else's request. Also I am an SA admin and am asking for this, ~officially\~. On behalf of the forums staff, thank you folks for all of the hard work you've done on this app.

**Comment by realModusOperandi** [comment]
Should be pretty straightforward, I'll get this in

**Comment by nolanw** [comment]
Implemented in 9eb8abffb. Thanks all!
