### ISSUE TITLE
Azure Pipelines doesn't appear to build pull requests

### ISSUE THREAD

**Issue by realModusOperandi** [Awful/Awful.app#971]
Is there a reason we don't have Azure Pipelines set up to build pull requests? For fixing builds it's nice to be able to open a PR to experiment without either spamming commits to master or rewriting history on master a bunch of times.

If there's a reason we can't, that's totally fine. Would be a nice-to-have but not necessary :).

**Comment by nolanw** [comment]
If I had a reason, it was to avoid sending build status emails for other branches. But I don't remember if that was actually the reason. I can take a look!

**Comment by nolanw** [comment]
Moved to Github Actions and I think it's set to build PRs. Gonna close this but please holler if it's not working!
